### ISSUE TITLE
USER STORY: ACCOUNT LOGIN

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy#11]
Epic: #2

As a **registered user** I can **login** so that **I can access my account**.

### Acceptance Criteria:

* The login link functions correctly
* The registered user is able to login to their account.

### Tasks:

- [x] Create login.html template
- [x] Add login link to navbar
- [x] Test login is possible
---
