### ISSUE TITLE
USER STORY: EDIT EVENT

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy#16]
Epic #3 

As a **user** I can **edit a post** so that **I can correct errors or add updated information**.

### Acceptance Criteria: 

* The user is able to edit an event they have created

### Tasks:

- [x] Create edit_event.html page
- [x] Add form to edit_event.html page
- [x] Add EditEventView class to views.py
- [x] Add url path to urls.py
- [x] Add links to events.html and event_detail.html
---
