### ISSUE TITLE
USER STORY: ADD EVENT

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy#17]
Epic #3

As a **user** I can **create an event** so that **I can add an event to the site**.

### Acceptance Criteria: 

* Users can click a link to add an event.

### Tasks:

- [x] Create add_event.html page
- [x] Add form to add_event.html page
- [x] Add AddEventView class to views.py
- [x] Add url path to urls.py
- [x] Add links to add events
---
