### ISSUE TITLE
USER STORY: DELETE EVENT

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy#18]
Epic #3 

As a **user** I can **delete an event** so that **I can remove a cancelled events from the site**.

### Acceptance Criteria: 

* The user is able to delete an event

### Tasks:

- [x] Create delete_event.html page
- [x] Add DeleteEventView class to views.py
- [x] Add url path to urls.py
- [x] Add links to events.html and event_detail.html
- [x] Add redirect to views.py
- [x] Test deletion of event
---
