### ISSUE TITLE
USER STORY: STYLE FORMS

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy#19]
Epic #3 

As a **user** I can **use styled forms to add events** so that **I can add the correct information easily**.

### Acceptance Criteria: 

* User can use a styled form to add an event

### Tasks:

- [ ] Create forms.py
- [ ] Add EventForm class
- [ ] Import Events form to views.py
- [ ] Add form_class to AddEventView class in views.py
- [ ] Test adding event via form
---
