### ISSUE TITLE
USER STORY: ADD FIELDS TO USER REGISTRATION FORM

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy#20]
Epic #2 

As a **user** I can **add my name and email to the register form** so that **I can auto complete fields in forms**.

### Acceptance Criteria: 

* The user registration form contains additional fields

### Tasks:

- [x] Add forms.py to pickers app
- [x] Add class to handle fields
- [x] Add forms class to views
---
