### ISSUE TITLE
USER STORY: CREATE USER ACCOUNT

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy#9]
Epic: #2

As a **site user** I can **create an account** so that **I can use the account to add content**.

### Acceptance Criteria: 

* A site user can create an account

### Tasks:

- [x] Create app to handle user authentication
- [x] Add urls.py file
- [x] Add new app to settings.py
- [x] Add paths to link to main urls.py
- [x] Create new templates and registration directories
- [x] Create login.html and register.html template pages
- [x] Create user register view in new views.py
- [x] Add path to new urls.py
- [x] Add redirect to settings.py
- [x] Successfully create a new user via the web pages
---
